name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore pefi.dynamicdns.sln

    - name: Build
      run: dotnet build pefi.dynamicdns.sln --no-restore -c Release

    - name: Run tests
      run: dotnet test pefi.dynamicdns.Tests/pefi.dynamicdns.Tests.csproj --no-build -c Release --verbosity normal

  build:

    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./pefi.dynamicdns/Dockerfile
        tags: petefield/pefi.dynamicdns:latest
        platforms: linux/amd64, linux/arm64
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"
        push: ${{ github.event_name != 'pull_request' }}
